### ISSUE TITLE
Use of "caption" breaks "krantz"

### ISSUE THREAD

**Issue by goranbrostrom** [yihui/bookdown-crc#13]
Using documentclass krantz removes the colon (:) in table captions ("Table 1:"  becomes "TABLE 1"), but the line

\usepackage[bf,singlelinecheck=off]{caption}

in "latex/preamble.tex" adds it back. Chapman & Hall doesn't like that, I get complaints in the proofreading phase. However, a workaround seems to be to just remove the line (and not use the 'caption' package). 

If it doesn't break anything, I suggest removing it.

Göran Broström

**Comment by yihui** [comment]
My proofreader never complained about the colon. It's simple enough to remove it, so I just did it in d774cd5b9be984c5e4a789291c168abab6e2ed29. Thank you!
